### PR TITLE
[PLAT-11566] Instrument navigation spans

### PR DESCRIPTION
**Pull request by gingerbenw**
## Goal

Automatically instrument navigation spans when using `react-native-navigation`

## Design

Add event listeners to the `Navigation` library to start and automatically end a navigation span when the route changes

**Note:** this approach also creates a navigation span for the initial route due to the way the end to end test is instrumented

## Changeset

- Add event listeners to plugin
- Add navigation span attributes

## Testing

- Update unit tests to check that a span in automatically started on route change
- Update end to end tests to check that a span is automatically started on a route change

### CODE REVIEW

**Comment by gingerbenw** [comment]
@gareththackeray Should we know what the previous route was from a navigation?

**Comment by gareththackeray** [comment]
> @gareththackeray Should we know what the previous route was from a navigation?

If we do know, I would suggest we include it as an attribute (`bugsnag.navigation.previous_route`).  If it is not possible or very difficult I think we can live without it.  We should also add it for React Navigation if we can.

**Review by yousif-bugsnag — APPROVED** [review]
LGTM - possibly out of scope for this PR but do we need an additional test to check that the app start instrumentation works?

**Comment by gingerbenw** [comment]
> LGTM - possibly out of scope for this PR but do we need an additional test to check that the app start instrumentation works?

Added `PLAT-11721` to instrument and test app start spans

**Comment by gingerbenw** [comment]
> > @gareththackeray Should we know what the previous route was from a navigation?
> 
> If we do know, I would suggest we include it as an attribute (`bugsnag.navigation.previous_route`). If it is not possible or very difficult I think we can live without it. We should also add it for React Navigation if we can.

Raised ticket `PLAT-11722` to add previous route attributes

**Pull request merged**
